package com.miso.blog.ai.job.code;

public enum AiJobFailureCode {
    OPENAI_API_KEY_MISSING,
    OPENAI_AUTH_FAILED,
    OPENAI_RATE_LIMIT,
    OPENAI_BAD_REQUEST,
    OPENAI_BAD_RESPONSE,
    OPENAI_NETWORK_ERROR,
    OPENAI_TIMEOUT,
    TARGET_NOT_FOUND,
    CONFLICT_STATE,
    VALIDATION_ERROR,
    UNKNOWN_ERROR
}
